CREATE  TABLE  IF  NOT  EXISTS  SESSION_LOCATION
(
	USER_ID  BIGINT  NOT  NULL  PRIMARY  KEY,CREATE_TIME  DATETIME  NOT  NULL,ACCESS_TIME  DATETIME,CLUSTER_NODE_ID  VARCHAR(255),SECRET_KEY  VARCHAR(255)  NOT  NULL,ONLINE  BIT  NOT  NULL  DEFAULT  FALSE
)
WITH  "TEMPLATE=PARTITIONED,BACKUPS=1,CACHE_NAME=SESSION_LOCATION_CACHE";